//! zoo-host: the on-chain half of openzoo-transmute.
//!
//! A Vercel deployment is, in Vercel's own terms, a set of Lambdas (`*.func`)
//! plus a `static/` tree plus a `config.json` route table. Vercel's node
//! bridge feeds each Lambda an `Invoke` event `{method, path, headers, body}`
//! and expects `{statusCode, headers, body}` back. This crate is that bridge,
//! re-hosted on Solana:
//!
//! * the Invoke event is the instruction data ([`wire::Req`])
//! * the bridge response is the return data + `sol_log_data` chunks
//!   ([`wire::Resp`])
//! * `static/` lives in asset PDAs ([`assets`])
//! * `@vercel/kv` lives in KV PDAs ([`kv`])
//! * the handler body is Rust generated by the transmuter, operating on a
//!   JS-semantics dynamic value ([`val::Val`])
//!
//! Generated programs call [`dispatch`] from their entrypoint.
#![no_std]
#![allow(clippy::needless_range_loop)]

extern crate alloc;

pub mod assets;
pub mod ctx;
pub mod fmt;
pub mod helpers;
pub mod site;
pub mod vm;
pub mod json;
pub mod kv;
pub mod val;
pub mod wire;

use alloc::{string::String, vec::Vec};
use pinocchio::{error::ProgramError, AccountView, Address, ProgramResult};

pub use ctx::Ctx;
pub use val::Val;
pub use wire::{Req, Resp};

/// A transmuted route handler. `Err(v)` is a thrown JS value.
pub type Route = fn(&mut Ctx) -> Result<(), Val>;

/// Instruction tags (first byte of instruction data).
pub const TAG_INVOKE: u8 = 0;
pub const TAG_ASSET_INIT: u8 = 1;
pub const TAG_ASSET_WRITE: u8 = 2;
pub const TAG_ASSET_CLOSE: u8 = 3;
// Shared runtime (zoo-vm) tags. Instruction data after the tag starts with
// the 32-byte site id, then the same payloads as the compiled-site tags.
pub const TAG_SITE_INIT: u8 = 16;
pub const TAG_SITE_SET_AUTHORITY: u8 = 17;
pub const TAG_VM_INVOKE: u8 = 18;
pub const TAG_VM_ASSET_INIT: u8 = 19;
pub const TAG_VM_ASSET_WRITE: u8 = 20;
pub const TAG_VM_ASSET_CLOSE: u8 = 21;
/// Path of a site's bytecode asset under the shared runtime.
pub const CODE_PATH: &str = "/.zoo/code.bin";

/// Custom program error: a KV account the handler needed was not passed.
/// The gateway reads the `ZOOK` log lines, adds the accounts and retries.
pub const ERR_KV_MISSING: u32 = 0x4b56_0001;
/// Custom program error: the caller is not the program's upgrade authority.
pub const ERR_NOT_AUTHORITY: u32 = 0x4b56_0002;
/// Custom program error: malformed instruction data.
pub const ERR_BAD_WIRE: u32 = 0x4b56_0003;

/// Entry used by generated programs.
///
/// `env` is the Lambda's `.vc-config.json` `environment` table, baked in at
/// build time.
pub fn dispatch(
    program_id: &Address,
    accounts: &mut [AccountView],
    data: &[u8],
    routes: &[Route],
    env: &[(&'static str, &'static str)],
) -> ProgramResult {
    let (tag, rest) = match data.split_first() {
        Some(x) => x,
        None => return Err(ProgramError::Custom(ERR_BAD_WIRE)),
    };
    match *tag {
        TAG_INVOKE => invoke(program_id, accounts, rest, routes, env),
        TAG_ASSET_INIT => assets::init(program_id, accounts, rest),
        TAG_ASSET_WRITE => assets::write(program_id, accounts, rest),
        TAG_ASSET_CLOSE => assets::close(program_id, accounts, rest),
        _ => Err(ProgramError::InvalidInstructionData),
    }
}

fn invoke(
    program_id: &Address,
    accounts: &mut [AccountView],
    data: &[u8],
    routes: &[Route],
    env: &[(&'static str, &'static str)],
) -> ProgramResult {
    let req = wire::parse_req(data).map_err(|_| ProgramError::Custom(ERR_BAD_WIRE))?;
    let route = routes
        .get(req.route as usize)
        .copied()
        .ok_or(ProgramError::InvalidInstructionData)?;
    let mut cx = Ctx::new(program_id, accounts, req, env);
    let outcome = route(&mut cx);
    if !cx.kv.missing.is_empty() {
        // Account discovery: tell the gateway which PDAs to add, then fail so
        // nothing half-applied is committed.
        for pda in cx.kv.missing.iter() {
            wire::log_kv_missing(pda);
        }
        return Err(ProgramError::Custom(ERR_KV_MISSING));
    }
    match outcome {
        Ok(()) => {}
        Err(thrown) => {
            // Uncaught throw == a Lambda crash == 500, same as Vercel.
            let msg: String = match &thrown {
                Val::Obj(_) => match thrown.get_str("message") {
                    Val::Undef => thrown.to_js_string(),
                    m => m.to_js_string(),
                },
                _ => thrown.to_js_string(),
            };
            cx.res = Resp::json_error(500, &msg);
            cx.sent = true;
        }
    }
    if !cx.sent {
        // Handler returned without responding: Vercel answers 504 for a
        // Lambda that never called res.end(); we mirror that.
        cx.res = Resp::json_error(504, "handler returned without a response");
    }
    let bytes: Vec<u8> = wire::encode_resp(&cx.res);
    wire::emit(&bytes);
    Ok(())
}
